openapi: 3.0.0
info:
  title: Git Diff API
  description: API for managing Git diffs
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

security:
  - BearerAuth: []
  - BasicAuth: []
  - CookieAuth: []
  - OidcAuth: []
  - SamlAuth: []

paths:
  /repos/{repo}/diff:
    get:
      tags:
        - Diff
      summary: Get diff
      description: Retrieves the diff between the working directory and the index or a commit
      operationId: getDiff
      parameters:
        - name: repo
          in: path
          description: Repository name or ID
          required: true
          schema:
            type: string
        - name: target
          in: query
          description: Target to compare against (HEAD, commit SHA, or empty for index)
          required: false
          schema:
            type: string
            default: HEAD
        - name: path
          in: query
          description: Path to filter the diff by
          required: false
          schema:
            type: string
        - name: context_lines
          in: query
          description: Number of context lines to include
          required: false
          schema:
            type: integer
            default: 3
        - name: ignore_whitespace
          in: query
          description: Ignore whitespace changes
          required: false
          schema:
            type: boolean
            default: false
        - name: format
          in: query
          description: Output format
          required: false
          schema:
            type: string
            enum: [unified, json]
            default: json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diff'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /repos/{repo}/diff/{commit1}..{commit2}:
    get:
      tags:
        - Diff
      summary: Compare two commits
      description: Retrieves the diff between two commits
      operationId: compareCommits
      parameters:
        - name: repo
          in: path
          description: Repository name or ID
          required: true
          schema:
            type: string
        - name: commit1
          in: path
          description: First commit SHA
          required: true
          schema:
            type: string
        - name: commit2
          in: path
          description: Second commit SHA
          required: true
          schema:
            type: string
        - name: path
          in: query
          description: Path to filter the diff by
          required: false
          schema:
            type: string
        - name: context_lines
          in: query
          description: Number of context lines to include
          required: false
          schema:
            type: integer
            default: 3
        - name: ignore_whitespace
          in: query
          description: Ignore whitespace changes
          required: false
          schema:
            type: boolean
            default: false
        - name: format
          in: query
          description: Output format
          required: false
          schema:
            type: string
            enum: [unified, json]
            default: json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diff'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

  /repos/{repo}/diff/{commit}:
    get:
      tags:
        - Diff
      summary: Get commit diff
      description: Retrieves the diff of a specific commit
      operationId: getCommitDiff
      parameters:
        - name: repo
          in: path
          description: Repository name or ID
          required: true
          schema:
            type: string
        - name: commit
          in: path
          description: Commit SHA
          required: true
          schema:
            type: string
        - name: path
          in: query
          description: Path to filter the diff by
          required: false
          schema:
            type: string
        - name: context_lines
          in: query
          description: Number of context lines to include
          required: false
          schema:
            type: integer
            default: 3
        - name: ignore_whitespace
          in: query
          description: Ignore whitespace changes
          required: false
          schema:
            type: boolean
            default: false
        - name: format
          in: query
          description: Output format
          required: false
          schema:
            type: string
            enum: [unified, json]
            default: json
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diff'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      in: cookie
      name: session_token
    OidcAuth:
      type: openIdConnect
      openIdConnectUrl: https://auth.example.com/.well-known/openid-configuration
    SamlAuth:
      type: apiKey
      in: header
      name: X-SAML-Assertion

  schemas:
    Diff:
      type: object
      properties:
        repo:
          type: string
          description: Repository name or ID
          example: "my-repo"
        from:
          type: string
          description: Source reference
          example: "HEAD"
        to:
          type: string
          description: Target reference
          example: "index"
        files:
          type: array
          description: Files in the diff
          items:
            $ref: '#/components/schemas/DiffFile'
        stats:
          type: object
          properties:
            total_files:
              type: integer
              description: Total number of files changed
              example: 3
            total_additions:
              type: integer
              description: Total number of additions
              example: 15
            total_deletions:
              type: integer
              description: Total number of deletions
              example: 5
            total_changes:
              type: integer
              description: Total number of changes
              example: 20
        url:
          type: string
          description: URL to the diff
          example: "https://api.example.com/v1/repos/my-repo/diff"
        html_url:
          type: string
          description: HTML URL to the diff
          example: "https://github.com/user/my-repo/compare/main..feature-branch"

    DiffFile:
      type: object
      properties:
        filename:
          type: string
          description: File name
          example: "src/main.js"
        old_filename:
          type: string
          description: Old file name (for renamed files)
          example: "src/old-main.js"
        status:
          type: string
          description: File status
          enum: [added, modified, deleted, renamed, copied]
          example: "modified"
        additions:
          type: integer
          description: Number of additions
          example: 5
        deletions:
          type: integer
          description: Number of deletions
          example: 2
        changes:
          type: integer
          description: Total number of changes
          example: 7
        blob_url:
          type: string
          description: URL to the blob
          example: "https://api.example.com/v1/repos/my-repo/blobs/def456abc7890123def456abc7890123def456ab"
        raw_url:
          type: string
          description: URL to the raw file
          example: "https://raw.githubusercontent.com/user/my-repo/main/src/main.js"
        contents_url:
          type: string
          description: URL to the file contents
          example: "https://api.example.com/v1/repos/my-repo/contents/src/main.js?ref=abc123def4567890abcdef1234567890abcdef12"
        patch:
          type: string
          description: Patch of changes
          example: "@@ -1,5 +1,6 @@\n function hello() {\n-  console.log('Hello');\n+  console.log('Hello World');\n }\n"
        diff:
          type: string
          description: Full diff
          example: "diff --git a/src/main.js b/src/main.js\nindex abc123..def456 100644\n--- a/src/main.js\n+++ b/src/main.js\n@@ -1,5 +1,6 @@\n function hello() {\n-  console.log('Hello');\n+  console.log('Hello World');\n }\n"
        hunks:
          type: array
          description: Diff hunks
          items:
            $ref: '#/components/schemas/DiffHunk'

    DiffHunk:
      type: object
      properties:
        old_start:
          type: integer
          description: Start line in the old file
          example: 1
        old_lines:
          type: integer
          description: Number of lines in the old file
          example: 5
        new_start:
          type: integer
          description: Start line in the new file
          example: 1
        new_lines:
          type: integer
          description: Number of lines in the new file
          example: 6
        header:
          type: string
          description: Hunk header
          example: "@@ -1,5 +1,6 @@"
        lines:
          type: array
          description: Lines in the hunk
          items:
            $ref: '#/components/schemas/DiffLine'

    DiffLine:
      type: object
      properties:
        old_line:
          type: integer
          description: Line number in the old file
          example: 1
        new_line:
          type: integer
          description: Line number in the new file
          example: 1
        type:
          type: string
          description: Line type
          enum: [context, added, deleted]
          example: "deleted"
        content:
          type: string
          description: Line content
          example: "  console.log('Hello');"
        no_newline_at_end:
          type: boolean
          description: Whether the line has no newline at the end
          example: false

    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: Error code
              example: invalid_request
            message:
              type: string
              description: Error message
              example: The request is malformed or contains invalid parameters
            details:
              type: object
              description: Additional error details
              example: {}

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'